spring.application.name=order-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:1235/order_service_db
spring.datasource.username=username
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
